# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('outros', '0003_auto_20170704_1608'),
        ('cortes', '0009_auto_20170704_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default='04/07/2017 16:09')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outros.Servico')),
            ],
        ),
    ]
