# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 03:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortes', '0013_auto_20170704_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 23, 9, 58, 904340)),
        ),
    ]
