# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 18:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortes', '0014_auto_20170704_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='hora',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='data',
            field=models.DateField(default=datetime.date(2017, 7, 5)),
        ),
    ]
