# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 18:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortes', '0015_auto_20170705_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
