# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 19:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20170704_1523'),
        ('clientes', '0001_initial'),
        ('vendas', '0004_auto_20170705_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime(2017, 7, 5, 15, 42, 15, 682398))),
                ('quantidade', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.Produto')),
            ],
        ),
        migrations.RemoveField(
            model_name='venda',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
