# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tel', models.IntegerField()),
                ('dataNasc', models.DateField()),
            ],
        ),
    ]
