# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
