# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outros', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servico',
            new_name='Servico1',
        ),
    ]
