# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outros', '0002_auto_20170704_1556'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servico1',
            new_name='Servico',
        ),
    ]
