# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outros', '0003_auto_20170704_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
