# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 04:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 0, 39, 48, 424517)),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='estado',
            field=models.CharField(choices=[('1', 'Aberto'), ('2', 'Fechado')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
